# Generated by Django 5.0.6 on 2024-06-27 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='body',
            field=models.TextField(default=django.utils.timezone.now, max_length=2200),
            preserve_default=False,
        ),
    ]
